#pragma once

#define BLADEBIT_VERSION_MAJ 1
#define BLADEBIT_VERSION_MIN 2
#define BLADEBIT_VERSION_REV 2

#define BLADEBIT_GIT_COMMIT "ae278e4919ed785a7354ccffa864733cf4d2bd9f"

#define BLADEBIT_VERSION \
    ((uint64)BLADEBIT_VERSION_MAJ) << 32 \
    ((uint64)BLADEBIT_VERSION_MIN) << 16 \
    ((uint64)BLADEBIT_VERSION_REV)

#define BLADEBIT_VERSION_STR \
    STR( BLADEBIT_VERSION_MAJ ) "." STR( BLADEBIT_VERSION_MIN ) "." STR( BLADEBIT_VERSION_REV ) 

