#pragma once

#define BLADEBIT_VERSION_MAJ    2
#define BLADEBIT_VERSION_MIN    0
#define BLADEBIT_VERSION_REV    0
#define BLADEBIT_VERSION_SUFFIX "dev"
#define BLADEBIT_VERSION_COMMIT ""

#define BLADEBIT_VERSION \
    ((uint64)BLADEBIT_VERSION_MAJ) << 32 \
    ((uint64)BLADEBIT_VERSION_MIN) << 16 \
    ((uint64)BLADEBIT_VERSION_REV)

#define BLADEBIT_VERSION_STR \
    STR( BLADEBIT_VERSION_MAJ ) "." STR( BLADEBIT_VERSION_MIN ) "." STR( BLADEBIT_VERSION_REV ) \
    "." BLADEBIT_VERSION_SUFFIX

